version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - API_KEY=dev-api-key-change-in-production
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=8000

  web-prod:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    environment:
      - FLASK_ENV=production
      - API_KEY=${API_KEY}
      - LOG_LEVEL=WARNING
    profiles:
      - production
    command: gunicorn -w 4 -b 0.0.0.0:8000 run:app